### ISSUE TITLE
Activation procedure

### ISSUE THREAD

**Issue by sotoniak** [schorschii/FsClock-Android#19]
Hi, how to activate the full version of the screensaver?
I have a device that is offline (kiosk) 
Where and how much should I send money and who will send me the code?
Thanks Tom

**Comment by schorschii** [comment]
Hi, please contact me via via support@georg-sieber.de and I tell you the details how to install and unlock the full version without the Play Store. Please note that an internet connection is temporarily required for activation. After activation, the device can be offline again.

**Comment by nitschis** [comment]
> Please note that an internet connection is temporarily required for activation.

Does this generally hold true if you purchase the full version? This is important to me as I pretty much never have the device online and don't want to go through the hassle of activating it in intervals.

If I buy it in the Play Store, can I activate the app from f-droid in the future?

Thanks.

**Comment by schorschii** [comment]
> activating it in intervals

The internet connection is only required once.

> If I buy it in the Play Store, can I activate the app from f-droid in the future?

No, the purchase in Play Store is different from the standalone version distributed in F-Droid and in the Github releases. For the standalone version, you need an unlock code.
