### ISSUE TITLE
Option to set horizontal/landscape position by default.

### ISSUE THREAD

**Issue by joaocandre** [schorschii/FsClock-Android#22]
As far as I understand, current versions of the app require "Auto-rotate" to be enabled in order to display the screen saver in landscape mode. It would nice to have an option to bypass the system settings and configure a display mode directly.
Also, the clock isn't centered/maximized when in landscape mode.

**Comment by schorschii** [comment]
Implemented in fc6263f376a08864e3c7e75907a42fd258e7617d
