### ISSUE TITLE
Fastlane

### ISSUE THREAD

**Issue by IzzySoft** [schorschii/FsClock-Android#34]
Glad to see you've added Fastlane structures!

* `full_description.txt`: could you please add an empty line before the bullet-point list, so it can be processed as Markdown? And maybe you could make the introductionary line a "full sentence", like `<i>Clock Screensaver</i> is a simple fullscreen clock screensaver.`?
* screenshots should be separate files, one per screenshot (not 1 image combining 3 screenshots)
* an `icon.png` is missing. This would become an issue should you switch to XML icons (as you currently have PNG icons in `res/`, that should work with F-Droid)

Thanks for taking care!

**Comment by schorschii** [comment]
Thanks for your tips!

**Comment by IzzySoft** [comment]
Thank you for the fast adjustment!
