### ISSUE TITLE
Show next alarm time

### ISSUE THREAD

**Issue by mdissel** [schorschii/FsClock-Android#36]
Show the next alarm ime if and when an alarm is setup

**Comment by schorschii** [comment]
See #33 

Already implemented and released in v1.10.0.

**Comment by mdissel** [comment]
Thanks. Not yet arrived in the play store...

**Comment by schorschii** [comment]
Yes, I stopped the v1.10.0 rollout in favor of the upcoming v1.11.0, which has some improvements.
