### ISSUE TITLE
Android 14 and Screensaver

### ISSUE THREAD

**Issue by weedy171** [schorschii/FsClock-Android#40]
Not sure if this is an issue or setup issue. I am having issues when my device is docker or charging where the screensaver will not appear. I can make it appear in the preview which looks great. I have the option to select while dock and charging but that seems not to help.

**Comment by schorschii** [comment]
Screensavers appear in dock/charging after the "screen timeout" time (adjustable in Android settings). Did you wait this time without turning the screen off manually?

Are other screensavers working?

**Comment by weedy171** [comment]
So  I have a minute timeout, The other screensaver clock do the same as well.

**Comment by schorschii** [comment]
> The other screensaver clock do the same as well.

So an other screensaver does **not** appear as well? Then it's a system issue, there is nothing I can do.
