### ISSUE TITLE
Hour hand JUMPS.

### ISSUE THREAD

**Issue by DiverAllen** [schorschii/FsClock-Android#43]
Can you do something to have the hour hand move during the hour?
In my screen shot you can see that the hour hand stays on the 6:00 position even though it is 6:59 or one minute before 7:00.
If I was only displaying the analog clock view I would have thought it was one minute to six instead of one minute to seven.  The analog clock looks like 5:59.
Here's a screenshot https://drive.google.com/file/d/1_ESthNAaGrsFv46vmIfoaT1POkNzRgdw/view?usp=sharing
Thanks.
For what it's worth - I have a Google Pixel 8 Pro.
Regards, A.

**Comment by schorschii** [comment]
That's true and already fixed in 2826adb (not released yet).

Thanks for reporting.
