### ISSUE TITLE
Landscape mode on charger/power plug

### ISSUE THREAD

**Issue by joaocandre** [schorschii/FsClock-Android#44]
Any plans to allow triggering landscape mode from charger plug? That's how I mostly use the app.

**Comment by schorschii** [comment]
Can you please describe your use case in more detail? Why should the app rotate to landscape when plugging in the charger?

**Comment by joaocandre** [comment]
I often use it as a table top clock, usually with the cable plugged. Obviously I can always open the app, but if both features are present, it streamlines the process.

**Comment by schorschii** [comment]
OK, so what you want is that it automatically opens when plugging in the charger. First I thought that you want it to rotate to landscape when plugging in the charger.

So the thing is that this is not possible anymore in recent Android versions. I already implemented this here, but it only works in old Android versions.
https://github.com/schorschii/FsClock-Android/blob/32ef242b11bea6cb392580aee60bd0167c9f9d8f/app/src/main/AndroidManifest.xml#L59

But nearly the same thing can be achieved by setting the clock as screensaver. Then you can connect your device to power and wait a minute until the screensaver starts. Isn't this a solution for you?

**Comment by schorschii** [comment]
Yes, that's right, landscape isn't available then. This and the no longer working automatic app start via `<action android:name="android.intent.action.ACTION_POWER_CONNECTED" />` are Android system restrictions. There is nothing I can do about it.
