### ISSUE TITLE
Will this work in new Amazon Fire TV Stick 4K Max ?

### ISSUE THREAD

**Issue by gitttt54** [schorschii/FsClock-Android#48]
Hello,
I saw this on the Appstore, installed it and started it and it worked.

I then put in the adb shell commands for autostarting as a screensaver, but nothing happens after a minute (or ten)

```
$ settings get system screen_off_timeout                                                                                                          
60000
$ settings get secure screensaver_components
systems.sieber.fsclock/systems.sieber.fsclock.FullscreenDream

```

Is this apk known to work on this particular platform? amazon shows it as "compatible".

**Comment by schorschii** [comment]
> Is this apk known to work on this particular platform? amazon shows it as "compatible".

It's in the official Amazon app store, so yes it's "compatible" (which means, from Amazon point of view, manually starting the app). But it is not officially supported by Amazon to change the system screensaver to a third-party app (for whatever reason)...

Looks like setting the screensaver to a third-party app does not work anymore in general on newer FireTV devices: https://github.com/theothernt/AerialViews/issues/127

**Comment by gitttt54** [comment]
Thank you very much for this information!

**Comment by schorschii** [comment]
A user told me that this command works on a Fire HD10 13th Gen:
```
adb shell settings put secure screensaver_default_component systems.sieber.fsclock/systems.sieber.fsclock.FullscreenDream
```
(screensaver_components -> screensaver_default_component, without "s")

Can you confirm this with your Fire TV Stick 4K Max, @gitttt54 ?

**Comment by gitttt54** [comment]
Hello and thank you for remembering me an the fact that it does not work on a firestick 4k!
this is what I typed in via adb console. (before and after installing your app again)

```
$ uname -a                                                                                                                                                             
Linux localhost 5.10.43-android12-9-gb9485240248a #1 SMP PREEMPT Thu Jul 18 16:21:07 UTC 2024 armv8l
$ settings put secure screensaver_default_component systems.sieber.fsclock/systems.sieber.fsclock.FullscreenDream                                                                
$ settings get secure screensaver_default_component                                                                                                                    
systems.sieber.fsclock/systems.sieber.fsclock.FullscreenDream

```

`screen_off_timeout` has the same value as in my first post, but it seems, nothing has changed (no "screensaver" is starting. starting the app manually works fine.

If I can be of more assistance please tell me.
